### ISSUE TITLE
server_settings gem was not found

### ISSUE THREAD

**Issue by tomohiro** [mixigroup/server_settings#4]
I tried installing sever_settings by `bundle install` and `gem install` but that was failed.

Anyway, I've installed by editing workaround in Gemfile like this:

```
gem 'server_settings', github: 'monsterstrike/server_settings'
```

This workaround is working well.

Finally, Do you have a plan of release to the rubygems.org?

**Comment by hirocaster** [comment]
Thanks, your proposal.
I just release it. https://rubygems.org/gems/server_settings
